<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="pallavi-testing" ignored="0" name="retry" tests="8" failures="2" timestamp="22 Jun 2019 15:41:44 GMT" time="0.124" errors="0">
  <testcase name="f" time="0.028" classname="pack1.RetryLogic">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="f" time="0.004" classname="pack1.RetryLogic">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="f" time="0.005" classname="pack1.RetryLogic">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="f" time="0.002" classname="pack1.RetryLogic">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at pack1.RetryLogic.f(RetryLogic.java:9)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f1" time="0.001" classname="pack1.RetryLogic">
    <skipped/>
  </testcase> <!-- f1 -->
  <testcase name="f1" time="0.001" classname="pack1.RetryLogic">
    <skipped/>
  </testcase> <!-- f1 -->
  <testcase name="f1" time="0.001" classname="pack1.RetryLogic">
    <skipped/>
  </testcase> <!-- f1 -->
  <testcase name="f1" time="0.001" classname="pack1.RetryLogic">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at pack1.RetryLogic.f1(RetryLogic.java:14)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- f1 -->
</testsuite> <!-- retry -->
